### ISSUE TITLE
Write a Coffea Processor built from a fast-flow config

### ISSUE THREAD

**Issue by benkrikler** [FAST-HEP/fast-carpenter#88]
From discussions with @lgray, it should be relatively easy to adapt the proto-PARSL back-end carpenter (https://gist.github.com/benkrikler/dc1d2b1fa291b8250a6a07be2b7fc7fa) to be a Coffea Processor.

We should then be able to use this with the PARSL backend of Coffea.  Adapting to the Spark backend will then need us to identify the necessary input / output variables of each stage.

This is a tracking issue for this feature.

**Comment by lgray** [comment]
Here's a gist to start things off:
https://gist.github.com/lgray/58cc92282168097efef9e2fab83f397a

**Comment by lgray** [comment]
The gist example is now functional and works with the following versions of FAST packages and coffea:
```
fast-carpenter     0.14.3   
fast-curator       0.3.2    
fast-flow          0.3.0    
fast-plotter       0.2.1 
coffea             0.6.13 
```
n.b. it is only shown to work with the local executors, I'm sure some whittling is needed to get everything smoothed over for parsl/spark/dask.


A few observations:
- FAST stages should be made less stateful, i.e. they should return something we can accumulate (like just underlying pandas dataframe) rather than being updated internally when passed data.
- FAST collectors should return the collected dataframe rather than writing things out (that should be up to the user, no?)
- FAST stages should be compatible with the various dataframe shims in coffea, since we do not necessarily receive data that is backed by a TTree!

**Comment by lgray** [comment]
I checked this today. The script in the gist works out of the box with the dask and parsl executors locally, just change out the executor and go. 

Dask and Parsl both have SGE, condor, and slurm interfaces. Go give them a try! @benkrikler 

You'll just have to make sure that the environments are ~synced at the login node and the worker. Shouldn't be too hard to work out. If you want things to work for Spark, we'll have to change how you interact with uproot TTrees a bit.

**Comment by benkrikler** [comment]
I'm closing this issue now since as of #102 we now have a Coffea backend on the master branch.  Currently it only uses the uproot executor, which I think is analogous to alphatwirl's multiprocessing mode.  It can be enabled by passing `--mode coffea:local` on the command line.  

Next steps will be to extend / replicate this to use the Parsl and Dask executors, but I'll put up a separate issue to cover this.  

We'll have to see how this interface plays out as well.  I'm not sure if a single command-line "mode" option will make sense, or if we'll need finer-grained controls as well.  We already provide options for the number of workers, the chunk size, and the maximum number of chunks per dataset to process; we'll have to monitor if others appear and if so, what mechanism to provide.

**Comment by lgray** [comment]
@benkrikler Given that all clusters are a bit different and you have to tweak settings, you'll probably need some configuration boilerplate in your yaml file where the workflow is defined.

Perhaps something like `--mode coffea:local` and `--mode coffea:cluster` and if it's coffea cluster it looks for a cluster config in the yaml file and sets up the right call to coffea.
